version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_SET_CHARSET_NAME: utf8mb4
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: graqt
    volumes:
      - ./example/sql:/docker-entrypoint-initdb.d